apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-webserver-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: web-container
        image: {{ .Values.imageName }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.webPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.webPort }}
          initialDelaySeconds: 3
          periodSeconds: 2
