apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-webserver-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: web-container
        image: {{ .Values.imageName }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.webPort }}
