name: CI-CD Build Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code from Repository
      uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Compile and Push Custom Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: xun0321/my-first-app:latest
    - name: Set up Helm Core
      uses: azure/setup-helm@v4
      with:
        version: 'v3.14.0'
    - name: Deploy Replicas to Local Cluster from Cloud
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        helm upgrade --install cloud-release ./my-devops-app --set replicaCount=3
        echo "=== PORT FORWARD ==="
        kubectl port-forward deployment/helm-webserver-deployment 8082:80 &
        sleep 10
        echo "==== INSPECTING THE LIVE CLOUD WEBPAGE LAYOUT ==="
        curl -s http://localhost:8082
        echo "=================================================" 
